from enum import Enum


class EnvironVariable(Enum):
    MYSQL_HOST = 'MYSQL_HOST'
    MYSQL_USER = 'MYSQL_USER'
    MYSQL_PASSWORD = 'MYSQL_PASSWORD'
    MYSQL_DATABASE = 'MYSQL_DATABASE'
    MYSQL_POOL_NAME = 'MYSQL_POOL_NAME'
    MYSQL_POOL_SIZE = 'MYSQL_POOL_SIZE'
